### ISSUE TITLE
back camera

### ISSUE THREAD

**Issue by marcosestini** [Kephson/html5qrcodereader#3]
the code works with the front camera of my smartphone, as can I read the qr-code from the back camera?

**Comment by adhitris** [comment]
using chrome from your smartphone ? forget it, use firefox and you can choose camera what you want to share

open this discussion :
https://groups.google.com/forum/#!topic/discuss-webrtc/i07T1X_DY94

**Comment by Kephson** [comment]
Thanks for the information. This coding example uses the default API of the browsers, some browsers allow you to access more than others.
