### ISSUE TITLE
Video feed freezes on Android 6 Chrome 52

### ISSUE THREAD

**Issue by sthag** [Kephson/html5qrcodereader#5]
I'm experiencing the problem that the code is working fine on desktop chrome 52 for example.
But on Android 6 with Chrome 52 the camera feed is displayed but freezes after one second.
The feed continues if the html element containing the video source is touched and moved permanently. As long as there is movement the video feed is updated. Without interaction the video stops.

Is there a solution to this problem?

**Comment by Kephson** [comment]
Hi, at the moment I don't know a solution for this problem.

**Comment by Kephson** [comment]
@sthag could you give me some more information about the script: did you use the Photobooth version or the Saycheese version?

**Comment by Kephson** [comment]
You could try the demonstration of this script: https://github.com/jhuckaby/webcamjs. I think I will integrate this in the next version.

**Comment by sthag** [comment]
I jumped through many different implementations here at github of the qrcode from lazarsoft. I experienced the same problem with some other repo and there was an easy solution. At some point a video tag is inserted into the dom and if it has the autoplay attribute it runs just fine. For more info see [this issue](https://github.com/dwa012/html5-qrcode/issues/46#issuecomment-246744118). Maybe this helps.

**Comment by Kephson** [comment]
I tried some changes for the scripts, but the video still freezes with Chrome in Android.
I updated the script with some changes for the say cheese version and this is the best version at the moment.

**Comment by SvilenStoianov** [comment]
Hope that there will be solution for this issue.

**Comment by Kephson** [comment]
I think there is no solution at the moment.
