### ISSUE TITLE
Works on Chrome only with https ?

### ISSUE THREAD

**Issue by laurasra** [Kephson/html5qrcodereader#6]
It seems that all the working examples with Chrome all have https, and my console says:

`getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS.`

Is there a way to go around that ? For me this means people can't use my site with Chrome, which can be a deal breaker for them.

**Comment by Kephson** [comment]
The easiest way would be to add SSL over HTTPS to your website, e.g. with Let's Encrypt, see https://letsencrypt.org/.
Information: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
