### ISSUE TITLE
Camera selection

### ISSUE THREAD

**Issue by olivierfaber** [Kephson/html5qrcodereader#7]
With google Chrome on Android 7.0, the camera selection doesnt list the camera's anymore.

**Comment by Kephson** [comment]
Hi, and what is the default selection? The front camera?

**Comment by olivierfaber** [comment]
Yes that's correct, the front camera.

**Comment by Kephson** [comment]
Ok, it's the same with Chrome 56 on Android 5.1.0. I will check this.

**Comment by goo-technology** [comment]
Hi, any update on this? Thank's!

**Comment by Kephson** [comment]
At the moment there is no time to check how this could work.

**Comment by sabrisangjaya** [comment]
Hi, any update on this? Thank's!

**Comment by Kephson** [comment]
At the moment there is no update

**Comment by Kephson** [comment]
At the moment I can't find any framework which is working with all devices, browsers and cameras.
