### ISSUE TITLE
Camera not working for mobile.

### ISSUE THREAD

**Issue by Vivu007** [Kephson/html5qrcodereader#8]
Thanks i used this for my website and it works great for the desktop however for the mobile the camera isn't opening. how should i modify script so that it works on the mobile also

**Comment by Kephson** [comment]
Hi, thanks for the feedback, it depends on the mobile device you are using, e.g. iOS, Android and on the browser you are using on the mobile device.

**Comment by Kephson** [comment]
At the moment I can't find any framework which is working with all devices, browsers and cameras.
